select * from XXCRM.ORGANIZATIONS
column name ORGANIZATION_ID,ORGANIZATION_NAME
SELECT * FROM XXCRM.XXSSG_TEST_TABLE
HEADER_ID,ORDER_NUMBER,ORDER_DATE,REMARKS,CUSTOMER_NAME,PHOTO_DATA,CUSTOMER_GENDER,FILE_DATA,ORGANIZATION_NAME,CUSTOMER_NUMBER,ORGANIZATION_ID,
FILE_LINK,PHOTO_LINK,ITEM_NAME,BAG_CEMENT_BM_PCC,BAG_CEMENT_AM_PCC,BAG_CEMENT_GOLD_OPC

CREATE TABLE XXCRM.XXSSG_TEST_TABLE (
    HEADER_ID int,
    ORDER_NUMBER int,
    ORDER_DATE date,
    REMARKS varchar(100),
    CUSTOMER_NAME varchar(100),
    PHOTO_DATA blob,
    CUSTOMER_GENDER varchar(100),
    FILE_DATA blob,
    ORGANIZATION_NAME varchar(100),
    CUSTOMER_NUMBER int,
    ORGANIZATION_ID int,
    FILE_LINK varchar(100),
    PHOTO_LINK varchar(100),
    ITEM_NAME varchar(100),
    BAG_CEMENT_BM_PCC varchar(100),
    BAG_CEMENT_AM_PCC varchar(100),
    BAG_CEMENT_GOLD_OPC varchar(100)
    
   
)
CREATE TABLE  XXCRM.ORGANIZATIONS(
 ORGANIZATION_ID int,
 ORGANIZATION_NAME varchar(100)

)
ALTER TABLE XXCRM.XXSSG_TEST_TABLE
MODIFY  FILE_LINK VARCHAR(500)

INSERT INTO XXCRM.ORGANIZATIONS(ORGANIZATION_ID, ORGANIZATION_NAME )
VALUES
  -- (101, 'SCBL')
 --  (161, 'SSCML')
 --  (401, 'SSCIL')
 --   (501, 'CEMCOA')
    (601,'SSGIL')
    select * from XXCRM.ORGANIZATIONS