/* Formatted on 12/11/2023 12:58:20 PM (QP5 v5.163.1008.3004) */
SELECT DISTINCT
       PAPF.EMPLOYEE_NUMBER AS EMPLOYEE_NUMBER,
       PPF.PAYROLL_NAME AS PAYROLL_NAME,
       PAPF.FIRST_NAME || ' ' || PAPF.MIDDLE_NAMES || ' ' || PAPF.LAST_NAME
          AS EMPLOYEE_NAME,
       SUBSTR (PJ.NAME, INSTR (PJ.NAME, '.') + 1) AS DESIGNATION,
       HAOU.NAME AS SECTION,
       HAOU1.NAME AS DEPT_NAME,
       HLA.LOCATION_CODE AS LOCATION,
       PPF.ATTRIBUTE1 AS PAYROLL_ORG_ID,
       PAPF.PERSON_ID AS PERSON_ID,
       PG.NAME AS GRADE,
       PPB.NAME AS SALARY_TYPE,
       PAAF.EMPLOYMENT_CATEGORY AS EMPLOYEE_CATEGORY,
       XESD.SHIFT AS SHIFT,
       XESD.STATUS AS ATTENDENCE_STATUS,
       PAPF.ATTRIBUTE4 AS OT_ELIGIBLE_STATUS,
       XESD.working_date
  FROM APPS.PER_ALL_PEOPLE_F PAPF,
       APPS.PER_ALL_ASSIGNMENTS_F PAAF,
       APPS.HR_ALL_ORGANIZATION_UNITS HAOU,
       APPS.PAY_PAYROLLS_F PPF,
       APPS.PER_JOBS PJ,
       APPS.PER_ORG_STRUCTURE_ELEMENTS POSE1,
       APPS.HR_ALL_ORGANIZATION_UNITS HAOU1,
       APPS.PER_ASSIGNMENT_STATUS_TYPES PAST,
       APPS.PER_GRADES PG,
       APPS.PER_PAY_BASES PPB,
       XXSSGIL.XXSSGIL_EMP_SHIFT_ALLOC_DET XESD,
       APPS.HR_LOCATIONS_ALL HLA
 WHERE     1 = 1
       --    AND PAPF.ATTRIBUTE4='Y'

       AND PAPF.BUSINESS_GROUP_ID = 84
       AND PJ.BUSINESS_GROUP_ID = 84
       AND PAST.USER_STATUS = 'Active Assignment'
       --AND PG.NAME IN (6, 7, 8, 9, 10, 11)

       AND PAPF.PERSON_ID = XESD.person_id
       AND PAPF.EMPLOYEE_NUMBER = :P_EMPLOYEE_ID
       --  AND PAPF.EMPLOYEE_NUMBER IN ('384')

       AND XESD.working_date = '14-Nov-23'         --Parameter :P_Working_Date
       AND PPB.PAY_BASIS_ID = PAAF.PAY_BASIS_ID
       AND PAAF.GRADE_ID = PG.GRADE_ID
       AND PAPF.PERSON_ID = PAAF.PERSON_ID
       AND PAPF.BUSINESS_GROUP_ID = PAAF.BUSINESS_GROUP_ID
       AND TRUNC (SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE
                               AND PAPF.EFFECTIVE_END_DATE
       AND TRUNC (SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE
                               AND PAAF.EFFECTIVE_END_DATE
       AND HAOU.ORGANIZATION_ID = PAAF.ORGANIZATION_ID
       AND PAAF.PAYROLL_ID = PPF.PAYROLL_ID
       AND PJ.JOB_ID = PAAF.JOB_ID
       AND PAAF.LOCATION_ID = HLA.LOCATION_ID
       AND PAAF.ORGANIZATION_ID = HAOU.ORGANIZATION_ID(+)
       AND PAAF.ORGANIZATION_ID = POSE1.ORGANIZATION_ID_CHILD(+)
       AND POSE1.ORGANIZATION_ID_PARENT = HAOU1.ORGANIZATION_ID(+)
       AND PAPF.CURRENT_EMPLOYEE_FLAG = 'Y'
       AND PAST.ASSIGNMENT_STATUS_TYPE_ID = PAAF.ASSIGNMENT_STATUS_TYPE_ID

---AND HAOU1.NAME != 'Sales'